[package]
name = "http_server_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
log = "0.4"
clap = { version = "4.4", features = ["derive"] }
futures-util = "0.3"